---

stages:
  - check
  - test
  - publish

.before_script: &pkgs_dependent_cc
  - apt update
  - apt install -y build-essential

cargo check:
  image: containers.dev.maio.me/sjohnson/containers/rust:latest
  stage: check
  tags:
    - amd64
  before_script: *pkgs_dependent_cc
  script:
    - cargo check

cargo tests amd64:
  image: containers.dev.maio.me/sjohnson/containers/rust:latest
  stage: test
  tags:
    - amd64
  before_script: *pkgs_dependent_cc
  script:
    - cargo test

cargo tests arm:
  image: containers.dev.maio.me/sjohnson/rpi-containers/rust:latest
  stage: test
  tags:
    - arm
  before_script: *pkgs_dependent_cc
  script:
    - cargo test

pages:
  image: containers.dev.maio.me/sjohnson/containers/rust:latest
  stage: publish
  tags:
    - amd64
  before_script: *pkgs_dependent_cc
  script:
    - cargo doc --target-dir . --no-deps --lib
    - mv doc public
  artifacts:
    paths:
      - public
  only:
    - master
