[package]
name = "rust_pca9685"
version = "0.1.0"
authors = ["Sean Johnson <sean.johnson@maio.me>", "Julian Itwaru <jrk57j@gmail.com>"]

[dependencies]
i2cdev = "0.4.0"
log = "0.4.0"
env_logger = "0.5.10"

[dev-dependencies]
env_logger = "0.5.10"